###################################################
### chunk number 1: 
###################################################
cat("Generated by Sweave from:\\\\")
cat(chartr("$", " ", "\\verb+$Source: /u/math/j40/cvsroot/lectures/src/SIntro/Rintro/Rnw/SXXquarry.Rnw.tex,v $+\\\\"))
cat(chartr("$", " ", "\\verb+$Revision: 1.20 $+\\\\"))
cat(chartr("$", " ", "\\verb+$Date: 2008/05/04 17:12:00 $+\\\\"))
cat(chartr("$", " ", "\\verb+$name:  $+\\\\"))
cat(chartr("$", " ", "\\verb+$Author: j40 $+\\\\"))


